version: "3.7"
services:
  notifications:
    build: .
    restart: always
    environment:
      RABBITMQ_SERVER: rabbitmq
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq


  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/


volumes:
  rabbitmq_data:
  rabbitmq_log:
  data:

networks:
  default:
  external:
    name: test