version: "3.7"
services:
  core:
    build: .
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - dev-net
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: 'rabbitmq'
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq/
#      - rabbitmq_log:/var/log/rabbitmq/

volumes:
  rabbitmq_data:
  rabbitmq_log:

networks:
  dev-net:
    driver: bridge