
version: "3"

services:
  minio:
    image: minio/minio:latest
    container_name: experiments_minio
    # restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - CONSOLE_ACCESS_KEY=minio
      - CONSOLE_SECRET_KEY=minio123
    command: server --address ":9000" --console-address ":9001" /data
    volumes:
      - minio_volume:/data

networks:
  dev-net:
    driver: bridge
volumes:
  minio_volume:
