package com.verylinkedin.core.utils;

public enum Fields {
    //CS FIELDS
    AI,
    VR,
    DEEP_LEARNING,
    MACHINE_LEARNING,
    WEB_DEVELOPMENT,
    EMBEDDED_SYSTEMS,
    NATURAL_LANGUAGE_PROCESSING,
    COMPUTER_VISION,
    MICROPROCESSORS,
    COMPUTER_ARCHITECTURE,
    MASSIVELY_SCALABLE_APPLICATIONS,
    DATABASES,
    CLOUD_COMPUTING,
    GIT,
    GAME_DEVELOPMENT,
    RESEARCH,
    BIOMEDICAL_ENGINEERING,
    SECURITY,
    WEB_SECURITY,
    MICROCONTROLLERS,
    ARDUINO,
    SENSORS,
    PROCESSORS,
    GRAPHICS_CARDS,
    JAVA,
    PYTHON,
    JAVASCRIPT,
    HASKELL,
    PROLOG,
    TYPESCRIPT,
    NODEJS,
    REACTJS,
    SPRINGBOOT,
    SERVERS,
    HTML,
    CSS,
    ANGULARJS,
    VUEJS,
    SWIFT,
    MAC_OS,
    WINDOWS,
    LINUX,
    UBUNTU,
    TERMINAL,
    VIM_EDITOR,
    BUSINESS_OF_SOFTWARE,
    GRAPHICS,
    COMPUTER_GRAPHICS,
    ALGORITHMS,
    ANALYSIS,
    DESIGN,
    NETWORKS,

    //NON PROGRAMMING ENGINEERING
    ARCHITECTURE,
    ELECTRICAL,
    CIVIL,
    AUTOMOTIVE,
    MATERIALS,
    PRODUCTION,
    SUSTAINABILITY,
    MEDICAL,
    NEUROSCIENCE,




    //NON ENGINEERING
    GARDENING,
    MARKETING,
    MEDIA,
    DENTISTRY,
    EDUCATIONAL,
    RETAIL,
    THERAPY,

    //Random stuff
    GAMING,
    FUNNY,
    INTERESTING,
    COOL,
    INSPIRATIONAL,
    MOTIVATIONAL,
    POLITICAL,




}
