server:
  port: 8082

spring:
  application:
    name: notifications
  rabbitmq:
    addresses: localhost:5672

rabbitmq:
  consumers: 5
  max-consumers: 5
  exchanges:
    internal: internal.exchange
  queues:
    notifications: notifications.queue
  routing-keys:
    internal-notifications: internal.notifications.routing.key
