server:
  port: 8080
  address: localhost

spring:
  application:
    name: core
  redis:
    port: 6379
    password: eminem7otob
    host: localhost
    timeToLive: 10800
  rabbitmq:
    addresses: localhost:5672
    listener:
      simple:
        default-requeue-rejected: false
