version: "3.7"
services:
  groups:
    build: .
    restart: always
    environment:
      RABBITMQ_SERVER: rabbitmq
      MONGO_SERVER: mongo
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    depends_on:
      - mongo


  mongo:
    container_name: 'mongo'
    image: "mongo:latest"
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

volumes:
  data:

networks:
  NETWORK:
    external: true
  default:
    external:
      name: test